# Generated by Django 4.0.6 on 2022-07-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
                ('StudentGender', models.CharField(max_length=10)),
                ('StudentEmail', models.EmailField(max_length=254)),
                ('StudentScore', models.CharField(max_length=3)),
            ],
        ),
    ]
